---
- name: Cleaning old config files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ apt_clean_old_config_files }}"

- name: handle Debian backports expired inRelease for old distros
  copy:
    content: |
      Acquire::Check-Valid-Until "0";
    dest: '/etc/apt/apt.conf.d/99backports'
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int <= 8

- name: Allow expired GPG key workaround
  copy:
    content: |
      APT::Get::AllowUnauthenticated "true";
      Acquire::AllowInsecureRepositories "true";
      Acquire::AllowDowngradeToInsecureRepositories "true";
    dest: /etc/apt/apt.conf.d/99allowUnauthenticated
    owner: root
    group: root
    mode: 0644
  when: apt_allow_unauthenticated|bool

- name: Be sure repo will be authenticated
  file:
    path: /etc/apt/apt.conf.d/99allowUnauthenticated
    state: absent
  when: not apt_allow_unauthenticated|bool
