---
- name: Update cache
  apt:
    update_cache: "{{ apt_cache_update }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Gather the package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- import_tasks: 10-custom-stuff.yml
  when: apt_play_custom_stuff

- name: Configure /etc/apt/preferences.d/ files
  copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ apt_preferences }}"
  when: apt_preferences|length > 0

- name: Add 32-bit architecture
  copy:
    content: "amd64\ni386\n"
    dest: /var/lib/dpkg/arch
    owner: root
    group: root
    mode: 0644
  when: apt_32_bit|bool

- name: Add some needed dependencies (ssl / gpg)
  apt:
    name: "{{ apt_needed_packages }}"
    state: present
  when: apt_needed_packages | difference(ansible_facts.packages)

- name: Add apt keys
  copy:
    content: "{{ item.content }}"
    dest: "/etc/apt/trusted.gpg.d/{{ item.name }}.asc"
    owner: root
    group: root
    mode: 0644
  loop: "{{ apt_keys }}"
  no_log: True

- name: Remove sources.list file
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: root
    group: root
    mode: "{{ item.mode | default(0644) }}"
  loop:
    - path: /etc/apt/sources.list
      state: absent
    - path: /etc/apt/sources.list~
      state: absent
    - path: /etc/apt/sources.list.save
      state: absent
    - path: /etc/apt/sources.list.d
      state: directory
      mode: "0755"
  tags: apt-sources-list-config

- name: Create sources.list.d main files
  template:
    src: "etc/apt/sources.list.d/{{ item }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item }}.list"
    owner: root
    group: root
    mode: 0644
  loop: "{{ apt_sources_list }}"
  tags: apt-sources-list-config
  notify:
    - apt update

- name: Create sources.list.d custom files
  copy:
    dest: "/etc/apt/sources.list.d/{{ item.dest }}"
    content: "{{ item.content }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ apt_custom_sources_list }}"
  tags: apt-sources-list-config
  notify:
    - apt update

- meta: flush_handlers

- import_tasks: 20-additional-packages.yml
