---
- name: Cleaning old config files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ apt_clean_old_config_files }}"

- name: Configure /etc/apt/preferences.d/ files
  copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
  with_items: "{{ apt_preferences }}"
  when: apt_preferences

- name: Add 32-bit architecture
  copy:
    content: "amd64\ni386\n"
    dest: /var/lib/dpkg/arch
  when: apt_32_bit

- name: Add ssl dependencies
  apt:
    name: "{{ item }}"
    update_cache: "{{ apt_cache_update }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - ssl-cert

- name: Add apt keys
  apt_key:
    data: "{{ lookup('file', 'etc/apt/keys/{{ item }}') }}"
    state: present
  with_items: "{{ apt_keys }}"

- name: Allow expired GPG key workaround
  copy:
    content: |
      APT::Get::AllowUnauthenticated "true";
      Acquire::AllowInsecureRepositories "true";
      Acquire::AllowDowngradeToInsecureRepositories "true";
    dest: /etc/apt/apt.conf.d/99allowUnauthenticated
  when: apt_allow_unauthenticated

- name: Be sure repo will be authenticated
  file:
    path: /etc/apt/apt.conf.d/99allowUnauthenticated
    state: absent
  when: not apt_allow_unauthenticated

- name: Configure sources.list
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items:
    - path: /etc/apt/sources.list
      state: absent
    - path: /etc/apt/sources.list~
      state: absent
    - path: /etc/apt/sources.list.d
      state: directory
  tags: apt-sources-list-config

- name: Configure HTTP sources.list
  template:
    src: "etc/apt/sources.list.d/{{ item }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item }}.list"
  with_items: "{{ apt_sources_list }}"
  register: result
  tags: apt-sources-list-config

- name: Update apt
  apt:
    update_cache: "yes"
  when: result.changed
  tags: apt-sources-list-config

- name: Install eatmydata package
  apt:
    name=eatmydata
    state=latest
  when: apt_eatmydata

- name: Configure eatmydata package
  file:
    src=/usr/bin/eatmydata
    dest={{ item }}
    state=link
  with_items:
    - '/usr/local/bin/apt'
    - '/usr/local/bin/apt-get'
    - '/usr/local/bin/aptitude'
  when: apt_eatmydata

- name: Configure Squid proxy
  apt:
    name: squid-deb-proxy-client
    state: latest
  when: apt_squid_proxy

- name: configure apt-proxy cache
  template:
    src: 'etc/apt/apt.conf.d/99proxy.j2'
    dest: '/etc/apt/apt.conf.d/99proxy'
